### ISSUE TITLE
Buttons improvements

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/search-bar#3]
- [x] Rename function to `SearchButtonPillColored`
https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonPillColored.jsx#L7
- [x] Add `...props` to components
https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/CloseButton.jsx#L7
https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButton.jsx#L7
https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonColored.jsx#L7
https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonPill.jsx#L7
https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonPillColored.jsx#L7
and then pass it to the component:
https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/CloseButton.jsx#L10
https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButton.jsx#L10
https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonColored.jsx#L10
https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonPill.jsx#L10
https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonPillColored.jsx#L10
- [x] Remove this style (see next one)
https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonColored.scss#L9-L11
https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonPillColored.scss#L9-L11
- [x] Add `color` prop to replace css style and pass it to `Icon component`
https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonColored.jsx#L7-L13
https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonPillColored.jsx#L7-L13

**Comment by montomos** [comment]
> * [x]  Rename function to `SearchButtonPillColored`
>   https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonPillColored.jsx#L7
> * [ ]  Add `...props` to components
>   https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/CloseButton.jsx#L7
>   
>   https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButton.jsx#L7
>   
>   https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonColored.jsx#L7
>   
>   https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonPill.jsx#L7
>   
>   https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonPillColored.jsx#L7
>   
>   and then pass it to the component:
>   https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/CloseButton.jsx#L10
>   
>   https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButton.jsx#L10
>   
>   https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonColored.jsx#L10
>   
>   https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonPill.jsx#L10
>   
>   https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonPillColored.jsx#L10
> * [ ]  Remove this style (see next one)
>   https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonColored.scss#L9-L11
>   
>   https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonPillColored.scss#L9-L11
> * [ ]  Add `color` prop to replace css style and pass it to `Icon component`
>   https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonColored.jsx#L7-L13
>   
>   https://github.com/rakuten-rex/search-bar/blob/c8378575396a5107dc1c56747a10a405d04454d0/src/components/ui/button/SearchButtonPillColored.jsx#L7-L13

This component is not exist and it is merged with SearchButtonPill
