### ISSUE TITLE
Component build types

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/search-bar#7]
### Stories

- [x] Create story for `Prominent` in `stories/Prominent/index.jsx` and move stories content from `stories/rex/simple-search/index.jsx`

- [x] Create story for `Secondary` in `stories/Secondary/index.jsx` and move stories content from `stories/rex/simple-search/index.jsx`

- [x] Remove `stories/rex/simple-search/index.jsx`

**Knobs** for `stories/Prominent/index.jsx` and `stories/Secondary/index.jsx`
- [x] Add knobs for `pill`

- [x] Add knob for `clearIcon`

- [x] Add knob for `placeholder`

- [x] Add knob for `defaultValue`

**Theme** 

- [x] Add theme options for `stories/Prominent/index.jsx` and `stories/Secondary/index.jsx`

### Component

- [x] Add `defaultValue` in `defaultProps` for `Prominent ` and `Secondary`

**Prominent**
- [x] Create new components under `src/components/Prominent`

Custom components
- [x] Create `SearchBar.jsx` with theme
- [x] Create `SearchBarTheme.jsx` without theme
- [x] Create `SearchBarPill.jsx` with theme
- [x] Create `SearchBarPillTheme.jsx` without theme

Export components
- [x] Add exports of `SearchBar`, `SearchBarTheme`, `SearchBarPill`, `SearchBarPillTheme`  to `src/components/Prominent/index.jsx`
example: `export { SearchBar } from './SearchBar';`

Stories
- [x] Replace current stories with `SearchBar`,  `SearchBarTheme`, `SearchBarPill`, and `SearchBarPillTheme`

**Secondary**
- [x] Create new components under `src/components/Secondary`

Custom components
- [x] Create `SearchBar.jsx` with theme
- [x] Create `SearchBarTheme.jsx` without theme
- [x] Create `SearchBarPill.jsx` with theme
- [x] Create `SearchBarPillTheme.jsx` without theme

Export components
- [x] Add exports of `SearchBar`, `SearchBarTheme`, `SearchBarPill`, `SearchBarPillTheme`  to `src/components/Secondary/index.jsx`
example: `export { SearchBar } from './SearchBar';`

Stories
- [x] Replace current stories with `SearchBar`,  `SearchBarTheme`, `SearchBarPill`, and `SearchBarPillTheme`

**Comment by montomos** [comment]
@claudio-moya  Pushed all the issues.  Please confirm them.
