### ISSUE TITLE
Browserstack tests

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/search-bar#8]
**Browserstack** 
UI tests (not screenshots) local testing

- [x] Prominent (normal and with theme)

- [x] Secondary (normal and with theme)
PC Devices
- [x] Safari
- [x] Firefox

- [x] Chrome

- [x] Edge

- [x]  IE11 (to see how it looks)
Mobile 
- [x] Use major devices iPhone 5+, Android OS v5+

**Browserstrack** 
Screenshots test (use major devices iPhone 5+, Android OS v5+)
- [x] Prominent (normal and with theme)
- [x] Secondary (normal and with theme)

PC Devices
- [x] Safari
- [x] Firefox

- [x] Chrome

- [x] Edge

- [x]  IE11 (to see how it looks)
Mobile 
- [x] Use major devices iPhone 5+, Android OS v5+

**Comment by claudio-moya** [comment]
- [ ] Second round of tests

**Comment by montomos** [comment]
@claudio-moya  I've done second round and there is no problem.
